# Base configs
baseurl: "https://speters.nl"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Patrick Speters"
subtitle: "See the world through my eyes!"
author: "Patrick Speters"
header:
 title: "Photography"
 subtitle: "by Patrick Speters"
footer:
 name: "Hey there, my name is Patrick"
 bio: "I am a hobby photographer from The Netherlands."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/PatrickS86/Speters.nl\">fork this repo on github</a> ;)"
web_design: "PS"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  linkedin: "https://in.linkedin.com/in/pspeters"
  github: "https://github.com/PatrickS86/"
