# Base configs
baseurl: "https://speters.nl"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-T4DKT1T9N9"

# UI configs
title: "Photography by Patrick Speters"
subtitle: "See the world through my eyes!"
author: "Patrick Speters"
header:
 title: "Photography"
 subtitle: "by Patrick Speters"
footer:
 name: "Hey there, my name is Patrick"
 bio: "I am hobby photographer from the Netherlands with a background in IT. My journey with photography began as a creative escape from my tech-focused career. Over the years, I have developed a keen eye for capturing moments that tell a story, whether it's the serene beauty of Dutch landscapes, the vibrant energy of urban life, or the intricate details of everyday objects.<br><br>

With my IT expertise, I have a unique perspective on the technical aspects of photography. I enjoy experimenting with different techniques and equipment, always seeking to improve my skills and expand my creative horizons. Whether I'm out exploring the countryside or navigating the bustling streets of a city, my camera is always by my side, ready to capture the perfect shot.<br><br>

Photography, for me, is more than just a hobby; it's a way to express my creativity and connect with the world around me. It's about finding beauty in unexpected places and sharing those moments with others. Through my lens, I aim to showcase the diversity and richness of our world, one photo at a time. "
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/PatrickS86/photography\">fork this repo on github</a> ;)"
web_design: "PS"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  linkedin: "https://in.linkedin.com/in/pspeters"
  github: "https://github.com/PatrickS86/"
